### ISSUE TITLE
ReactiveRawAutocomplete doesn't work if I delete the text in the field to clear it

### ISSUE THREAD

**Issue by sgehrman** [artflutter/reactive_forms_widgets#47] opened 2022-04-10 22:00 UTC
I have a state popup.  I select a state and that works, but if I delete the state, it doesn't update the form data.

**Comment by vasilich6107** [comment] 2022-04-10 22:29
@sgehrman could you provide copypasta or reproduction code?

**Comment by vasilich6107** [comment] 2022-04-15 12:12
@sgehrman any feedback?

**Comment by vasilich6107** [comment] 2022-05-06 17:51
Closing due to missing feedback

**Closed by vasilich6107** 2022-05-06 17:51 UTC
